version: "3.11"

services:
  llm:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: llm
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/models:/models
    command: >
      -m /models/bloomz-1b1-Q8_0.gguf
      --port 8000
      --host 0.0.0.0
      -n 4096
      --chat-template chatml
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    healthcheck:
      test: curl -f http://localhost:8000/health || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    networks:
      - llm-lab

# === Network ===
networks:
  llm-lab:
    name: llm-lab
    driver: bridge
    
